// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqypqfugkchxcrxepkst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxeXBxZnVna2NoeGNyeGVwa3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTAzNjksImV4cCI6MjA2OTY4NjM2OX0.ZAwLfQ9sPTRqQvIw5Ru39G11U5N00C2-EXVL9lAyZiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});